---
PLAINTEXT_VARIABLES:
    AWS_REGION: us-east-1
    ENVISIONWARE_DB_PORT: 3306
    ENVISIONWARE_DB_NAME: lasttwodays
    SIERRA_DB_PORT: 1032
    SIERRA_DB_NAME: iii
    REDSHIFT_DB_NAME: qa
    ENVISIONWARE_BATCH_SIZE: 500
    S3_BUCKET: bic-poller-states-qa
    S3_RESOURCE: pc_reserve_poller_state.json
    PC_RESERVE_SCHEMA_URL: https://qa-platform.nypl.org/api/v0.1/current-schemas/PcReserve
    KINESIS_BATCH_SIZE: 500
    SIERRA_TIMEOUT: 5
    MAX_SIERRA_ATTEMPTS: 5
ENCRYPTED_VARIABLES:
    ENVISIONWARE_DB_HOST: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGwwagYJKoZIhvcNAQcGoF0wWwIBADBWBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDAuBv/BphGCF+7eZXQIBEIApcoNy31Pd5JJDeeAmSKF8bGWMOZPLx9GgSMNxY1DTab6tICcqGK+onys=
    ENVISIONWARE_DB_USER: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGcwZQYJKoZIhvcNAQcGoFgwVgIBADBRBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDBYJiqjEoMyidrOt4QIBEIAk8jOvhrYElM4VzBEZ4pGnO7Dhr7R04mEU5y6mTqe+jUHEZMe9
    ENVISIONWARE_DB_PASSWORD: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGwwagYJKoZIhvcNAQcGoF0wWwIBADBWBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDFwhlhusjkreznM2MQIBEIApuLr9ardFTWoypuEPmb2qGhzrUz4qwOwVVhovD6u40i+kGEXTPfwO/yQ=
    SIERRA_DB_HOST: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGwwagYJKoZIhvcNAQcGoF0wWwIBADBWBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDL6zq0QQYBhdW4rz8gIBEIApxucxIVAb1Ec4uHUAwxRZcvC8OAZxuj/oJAkhCPh8sPJJ08w3ECoXoKk=
    SIERRA_DB_USER: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGkwZwYJKoZIhvcNAQcGoFowWAIBADBTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDAOwCAfLLsbty144MwIBEIAm1K82kx4DC41QMs3le1mDww52Ghys0MYZCpbhIUXTC1gKU+w1/GI=
    SIERRA_DB_PASSWORD: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGkwZwYJKoZIhvcNAQcGoFowWAIBADBTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDDOieLBvR+wmGGIJmgIBEIAmT5E9fH6+mxR96zipllWwre4BZdH9Gc0yJBND3ILuAq0+1lLk73g=
    REDSHIFT_DB_HOST: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAKIwgZ8GCSqGSIb3DQEHBqCBkTCBjgIBADCBiAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzfC7it2NYa1YnFy+4CARCAW1NrqGfSfPptEF4epEXl8Hr6ntrJcZ0DE1GeGt2c2mMnMt7hcim39NTgxHvi5DIldF4J2UJzgG0KBs5UGRU9dyjrQu5zLfdB8Kv50d1lHfvqM2aDQAK0SQ188BY=
    REDSHIFT_DB_USER: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGgwZgYJKoZIhvcNAQcGoFkwVwIBADBSBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDNEI2+MTdt0gsFvbigIBEIAlbvlZMJqypKJEqi1fyIW2Hfkbyj4Win8XRNK+cintKCh1PtMOaw==
    REDSHIFT_DB_PASSWORD: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHIwcAYJKoZIhvcNAQcGoGMwYQIBADBcBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJ8vJoancurH6emDawIBEIAvmBR9HZ3ESBrsyfxxoqiqIqlon/rTt0zieAfsYRlk4eFzg1MXRc9wnHvOuAgSrA0=
    KINESIS_STREAM_ARN: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAJwwgZkGCSqGSIb3DQEHBqCBizCBiAIBADCBggYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwdphjNF+nlFgpgL3ECARCAVcjhgjKAhkHqR8WfMnH7NhfEC3oJQWpJkML6xAu3da9JVTU/b1/3QOyJOHJ1udtgIi5U4tILtb6H1Bnq4ZJI4eK5DK0OaO33hDfZqlTCj1J4XCB6dKU=
    BCRYPT_SALT: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHsweQYJKoZIhvcNAQcGoGwwagIBADBlBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDFqhoI9xSv6texISOgIBEIA4dj5hPgp5DZ4sg0MmWdjZ0oh5X3+4dEMijJxgaeE7S5xOfNHRXU92wHHPbOlwtc0ytRiOuONNZLo=
...